version: "3.7"
services:
  # ====================================================================================================================
  # POSTGRES SERVER
  # ====================================================================================================================
  pg-docker:
    image: postgres:14-alpine
    container_name: dev-postgresql
    environment:
      POSTGRES_DB: npi
      POSTGRES_PASSWORD: 1234567
    ports:
      - 5434:5432
    volumes:
      - ./.data/postgresql/data:/var/lib/postgresql/data
      - ./create.sql:/docker-entrypoint-initdb.d/create.sql
    networks:
      - dev-network
  # ====================================================================================================================
  # Spring Boot Application
  # ====================================================================================================================
  npi-docker:
    # build: ./dockerfile/backend
    container_name: dev-npi
    image: lucasferreiraz/npi-api:1.0
    ports:
      - 8080:8080
    environment:
      db-url: jdbc:postgresql://pg-docker:5432/npi
      db-username: postgres
      db-password: 1234567
    depends_on:
      - pg-docker
    networks:
      - dev-network
  # ====================================================================================================================
  # Angular Application
  # ====================================================================================================================
  front-docker:
    # build: ./dockerfile/frontend
    container_name: dev-front
    image: lucasferreiraz/npi-front:1.0
    ports:
      - 4200:80
    depends_on:
      - npi-docker
    networks:
      - dev-network
# ======================================================================================================================
# REDE
# ======================================================================================================================
networks:
  dev-network:
    driver: bridge